RESEND_WINDOW_MINUTES = 15
RESEND_LIMIT_PER_USER_WINDOW = 3
RESEND_LIMIT_PER_IP_WINDOW = 10

LOGIN_FAILURE_THRESHOLD = 5
LOGIN_LOCKOUT_DURATION_MINUTES = 15
LOGIN_ATTEMPT_WINDOW_MINUTES = 15

SESSION_COOKIE_NAME = "if_session"
SESSION_TTL_DAYS = 1
SESSION_TTL_HOURS = 24

VERIFY_TOKEN_TTL_HOURS = 24
