import type { Locale } from './i18n';
const en = {
  setup: 'Factory setup',
  ready: 'Ready to bid',
  incomplete: 'Complete setup before bidding',
  verify: 'Verify your email first.',
  company: 'Company name',
  contact: 'Contact name',
  phone: 'Phone',
  saveProfile: 'Save company details',
  location: 'Company location',
  saveLocation: 'Save location',
  categories: 'Production categories',
  search: 'Search categories',
  saveCategories: 'Confirm selected categories',
  removal:
    'Removing a category blocks new bids and selection of open bids in that category. Existing inventory and signed work are preserved.',
  request: 'Request a category',
  name: 'Proposed name',
  description: 'Short description',
  parent: 'Parent category',
  none: 'No parent',
  submit: 'Submit for review',
  pending: 'Pending review',
  approved: 'Approved',
  rejected: 'Rejected',
  waiting:
    'Save a draft while waiting. Pending categories cannot be published or used for bidding.',
  draft: 'Product / inventory draft',
  drafts: 'Saved drafts',
  resume: 'Resume',
  newDraft: 'New draft',
  product: 'Product',
  newProduct: 'New product draft',
  category: 'Category',
  unit: 'Unit',
  quantity: 'Available stock quantity',
  price: 'Price per unit',
  currency: 'Currency',
  stock: 'Stock / dispatch location',
  save: 'Save draft',
  publish: 'Publish available stock',
  stockOnly: 'Enter stock available now. Future production capacity is not available stock.',
  saved: 'Saved',
  published: 'Published',
  error: 'Could not complete this action. Review the fields and try again.',
  retry: 'Retry',
  loading: 'Loading…',
  empty: 'No categories found',
  emptyDrafts: 'No saved drafts',
  review: 'Category review',
  link: 'Link existing category, or create a new category',
  create: 'Create new category',
  note: 'Decision reason',
  approve: 'Approve',
  reject: 'Reject',
  fallback: 'Missing translations use the original catalogue label.',
  next: 'Complete company details, confirm categories, then publish at least one stock offering.',
  select: 'Choose an existing category. Request a missing category below.',
  whole: 'Bids must fulfil the entire request.',
  blocked: 'Complete factory setup first',
  attributes: 'Product attributes',
  region: 'Region',
  city: 'City',
  street: 'Street',
  country: 'Country',
};
type Copy = typeof en;
const ru: Copy = {
  setup: 'Настройка производства',
  ready: 'Можно подавать предложения',
  incomplete: 'Завершите настройку перед подачей предложений',
  verify: 'Сначала подтвердите email.',
  company: 'Название компании',
  contact: 'Контактное лицо',
  phone: 'Телефон',
  saveProfile: 'Сохранить данные компании',
  location: 'Адрес компании',
  saveLocation: 'Сохранить адрес',
  categories: 'Категории продукции',
  search: 'Поиск категорий',
  saveCategories: 'Подтвердить выбранные категории',
  removal:
    'Удаление категории блокирует новые предложения и выбор открытых предложений в ней. Складские записи и подписанные договоры сохраняются.',
  request: 'Предложить категорию',
  name: 'Название категории',
  description: 'Краткое описание',
  parent: 'Родительская категория',
  none: 'Без родительской категории',
  submit: 'Отправить на рассмотрение',
  pending: 'На рассмотрении',
  approved: 'Одобрено',
  rejected: 'Отклонено',
  waiting:
    'Пока заявка рассматривается, можно сохранить черновик. До одобрения категории публикация и подача предложений недоступны.',
  draft: 'Черновик товара и складской записи',
  drafts: 'Сохранённые черновики',
  resume: 'Продолжить',
  newDraft: 'Новый черновик',
  product: 'Товар',
  newProduct: 'Черновик нового товара',
  category: 'Категория',
  unit: 'Единица измерения',
  quantity: 'Количество в наличии',
  price: 'Цена за единицу',
  currency: 'Валюта',
  stock: 'Адрес склада и отгрузки',
  save: 'Сохранить черновик',
  publish: 'Опубликовать товар в наличии',
  stockOnly:
    'Укажите товар, который уже есть в наличии. Будущая производственная мощность не считается складским запасом.',
  saved: 'Сохранено',
  published: 'Опубликовано',
  error: 'Не удалось выполнить действие. Проверьте поля и повторите попытку.',
  retry: 'Повторить',
  loading: 'Загрузка…',
  empty: 'Категории не найдены',
  emptyDrafts: 'Нет сохранённых черновиков',
  review: 'Рассмотрение категорий',
  link: 'Выберите существующую категорию или создайте новую',
  create: 'Создать категорию',
  note: 'Причина решения',
  approve: 'Одобрить',
  reject: 'Отклонить',
  fallback: 'Если перевода нет, показано исходное название из каталога.',
  next: 'Заполните данные компании, подтвердите категории и опубликуйте хотя бы один товар в наличии.',
  select: 'Выберите категорию из каталога. Недостающую категорию можно предложить ниже.',
  whole: 'Предложение должно покрывать весь объём заявки.',
  blocked: 'Сначала завершите настройку производства',
  attributes: 'Характеристики товара',
  region: 'Регион',
  city: 'Город',
  street: 'Улица',
  country: 'Страна',
};
const kk: Copy = {
  setup: 'Өндірісті баптау',
  ready: 'Ұсыныс беруге дайын',
  incomplete: 'Ұсыныс бермес бұрын баптауды аяқтаңыз',
  verify: 'Алдымен email мекенжайын растаңыз.',
  company: 'Компания атауы',
  contact: 'Байланыс тұлғасы',
  phone: 'Телефон',
  saveProfile: 'Компания деректерін сақтау',
  location: 'Компания мекенжайы',
  saveLocation: 'Мекенжайды сақтау',
  categories: 'Өнім санаттары',
  search: 'Санаттарды іздеу',
  saveCategories: 'Таңдалған санаттарды растау',
  removal:
    'Санатты алып тастау осы санатта жаңа ұсыныс беруді және ашық ұсынысты таңдауды тоқтатады. Қойма жазбалары мен қол қойылған шарттар сақталады.',
  request: 'Санат ұсыну',
  name: 'Санат атауы',
  description: 'Қысқаша сипаттама',
  parent: 'Жоғарғы санат',
  none: 'Жоғарғы санатсыз',
  submit: 'Қарауға жіберу',
  pending: 'Қаралуда',
  approved: 'Мақұлданды',
  rejected: 'Қабылданбады',
  waiting:
    'Өтінім қаралғанша нобайды сақтауға болады. Санат мақұлданғанға дейін жариялау және ұсыныс беру қолжетімсіз.',
  draft: 'Тауар мен қойма жазбасының нобайы',
  drafts: 'Сақталған нобайлар',
  resume: 'Жалғастыру',
  newDraft: 'Жаңа нобай',
  product: 'Тауар',
  newProduct: 'Жаңа тауар нобайы',
  category: 'Санат',
  unit: 'Өлшем бірлігі',
  quantity: 'Қолда бар саны',
  price: 'Бірлік бағасы',
  currency: 'Валюта',
  stock: 'Қойма және жөнелту мекенжайы',
  save: 'Нобайды сақтау',
  publish: 'Қолда бар тауарды жариялау',
  stockOnly:
    'Қазір қолда бар тауар санын көрсетіңіз. Болашақ өндіріс қуаты қойма қоры болып саналмайды.',
  saved: 'Сақталды',
  published: 'Жарияланды',
  error: 'Әрекет орындалмады. Өрістерді тексеріп, қайталап көріңіз.',
  retry: 'Қайталау',
  loading: 'Жүктелуде…',
  empty: 'Санаттар табылмады',
  emptyDrafts: 'Сақталған нобайлар жоқ',
  review: 'Санаттарды қарау',
  link: 'Бар санатты таңдаңыз немесе жаңасын жасаңыз',
  create: 'Санат жасау',
  note: 'Шешім себебі',
  approve: 'Мақұлдау',
  reject: 'Қабылдамау',
  fallback: 'Аудармасы болмаса, каталогтағы бастапқы атау көрсетіледі.',
  next: 'Компания деректерін толтырыңыз, санаттарды растаңыз және қолда бар кемінде бір тауарды жариялаңыз.',
  select: 'Каталогтан санат таңдаңыз. Жетіспейтін санатты төменде ұсынуға болады.',
  whole: 'Ұсыныс өтінімдегі толық көлемді қамтуы тиіс.',
  blocked: 'Алдымен өндірісті баптауды аяқтаңыз',
  attributes: 'Тауар сипаттамалары',
  region: 'Өңір',
  city: 'Қала',
  street: 'Көше',
  country: 'Ел',
};
export const categoryCopy = (locale: Locale): Copy => ({ en, ru, kk })[locale];
